# This is a basic workflow to help you get started with Actions

name: Giting Started File

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run Ls Command
        run: echo ${{ env.SHIT_VAR }}


      # Runs a set of commands using the runners shell
#      - name: Run Shell Script
#        run: sh ./excute.sh
#
#      - name: Set up SSH keys
#        uses: webfactory/ssh-agent@v0.5.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#          passphrase: ${{ secrets.SSH_PASSPHRASE }}
#
#      - name: Deploy code
#        run: |
#          ssh -o StrictHostKeyChecking=no allin1@190.92.178.146 "ls"
